finish error handling
MakesApp/movie-app-backend pull request #15
Opened 2023-02-08 12:47 UTC by ashgolan

2023-02-13 10:03 UTC, pini85 requested changes

2023-02-13 10:03 UTC, pini85 commented on components/movies/movie.controllers.js
> -import {
please resolve conflicts

2023-02-19 06:55 UTC, AmeerLalaDeveloper commented on components/movies/movie.controllers.js
> +	// eslint-disable-next-line no-unused-vars
add this rule to eslint

2023-02-19 06:56 UTC, AmeerLalaDeveloper commented on components/movies/movie.routes.js
> +	// eslint-disable-next-line no-unused-vars
??? why u need to create movie

2023-02-19 09:55 UTC, merged