auth with google
MakesApp/movie-app-backend pull request #19
Opened 2023-02-20 15:26 UTC by ashgolan

2023-02-20 16:00 UTC, AmeerLalaDeveloper commented on index.js
> +	cookieSession({ name: 'session', keys: ['lama'], maxAge: 24 * 60 * 60 * 100 })
change keys to movieApp

2023-02-21 11:51 UTC, pini85 requested changes

2023-02-21 11:51 UTC, pini85 commented on index.js
> +	cookieSession({ name: 'session', keys: ['lama'], maxAge: 24 * 60 * 60 * 100 })
the cookie keys should come from a env. Make it a long unique one

2023-02-21 11:51 UTC, pini85 commented on passport.js
> +import { Strategy as GoogleStrategy } from 'passport-google-oauth20';
passport.js should be under services

2023-02-21 11:51 UTC, pini85 commented on passport.js
> +			callbackURL: '/auth/google/movie-app',
best practice to add the callbackURL with callback. eg : "/auth/google/callback"

2023-02-21 11:51 UTC, pini85 commented on passport.js
> +			done(null, profile);
I would like to see in this PR also logic to save the user in the DB if does not exists. And retrieve an existing user.

2023-02-21 11:51 UTC, pini85 commented on passport.js
> +	done(null, user);
deserialize users from our db

2023-02-21 11:51 UTC, pini85 commented on routes/auth.js
> +	'/google',
please use as the path auth/google

2023-02-21 11:51 UTC, pini85 commented on routes/auth.js
> +const CLIENT_URL = 'http://localhost:3000/';
this is only working for local. How about in production? Also put them in our env files.

2023-02-22 08:25 UTC, ashgolan commented on passport.js
> +			callbackURL: '/auth/google/movie-app',
i dont understand what callback should we create

2023-02-22 08:25 UTC, ashgolan commented on passport.js
> +	done(null, user);
??

2023-02-22 08:26 UTC, ashgolan commented on routes/auth.js
> +	})
??

2023-02-22 12:55 UTC, ashgolan commented on passport.js
> +import { Strategy as GoogleStrategy } from 'passport-google-oauth20';
done

2023-02-22 12:57 UTC, ashgolan commented on passport.js
> +			done(null, profile);
done

2023-02-28 10:35 UTC, closed without merging